# Generated by Django 4.0.6 on 2022-07-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimetable',
            name='time',
        ),
        migrations.AddField(
            model_name='datetimetable',
            name='yo',
            field=models.CharField(default=1, max_length=21),
            preserve_default=False,
        ),
    ]
