# Generated by Django 4.0.6 on 2022-07-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_datetimetable_time_datetimetable_yo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimetable',
            name='yo',
        ),
        migrations.AddField(
            model_name='datetimetable',
            name='time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
