# Generated by Django 4.0.6 on 2022-07-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_datetimetable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimetable',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
