# Generated by Django 4.0.6 on 2022-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_datetimetable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimetable',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
